context:
  version: "0.3.20"

package:
  name: publint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/publint/-/publint-${{ version }}.tgz
  sha256: 2adc3c63d401745de2bbc2d35a8b732705be7c73e8b7687264dece82d26aa276

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - publint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint packaging errors
  homepage: https://publint.dev/
  repository: https://github.com/bluwy/publint

extra:
  recipe-maintainers:
    - danielnachun
