context:
  version: "0.3.24"

package:
  name: publint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/publint/-/publint-${{ version }}.tgz
  sha256: 83ad64151c95c63a4347635bbe6b67719fc105a053c9cedf7b785d896719e7c0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - publint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint packaging errors
  homepage: https://publint.dev/
  repository: https://github.com/bluwy/publint

extra:
  recipe-maintainers:
    - danielnachun
