context:
  version: "0.3.6"

package:
  name: publint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/publint/-/publint-${{ version }}.tgz
  sha256: c0a07052f40966800b16838ec4a3b7ac138319f391e37f6a3a873c00dbd9b469

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - publint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint packaging errors
  homepage: https://publint.dev/
  repository: https://github.com/bluwy/publint

extra:
  recipe-maintainers:
    - danielnachun
