context:
  version: "0.3.23"

package:
  name: publint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/publint/-/publint-${{ version }}.tgz
  sha256: 93a1cad5a9ccb6a8d9a71f474b180428356b050ebf4aed78728f44ea6a013f05

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - publint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Lint packaging errors
  homepage: https://publint.dev/
  repository: https://github.com/bluwy/publint

extra:
  recipe-maintainers:
    - danielnachun
